#vi:ft=systemd


[Content]
Packages=
    gvfs
    gvfs-mtp
    nautilus
    ghostty-nautilus
    yazi
    eza
    chafa
    bat
    zoxide
    fzf
    libqalculate
    lazygit
    polkit-kde-agent
    brightnessctl
    pipewire
    pipewire-jack
    pipewire-alsa
    wireplumber
    pipewire-audio
    blueman
    grim
    gvfs
    gvfs-mtp
    network-manager-applet
    playerctl
    rofi
    slurp
    sway
    swaybg
    swayidle
    swaylock
    system-config-printer
    waybar
    wl-clipboard
    wlsunset
    cliphist
    niri
    sddm
    ghostty
    zathura
    xdg-user-dirs-gtk
    xdg-desktop-portal-gtk
    xdg-desktop-portal-gnome
    xdg-desktop-portal-wlr
    waybar
    mako
    rofi
    fuzzel
    flatpak
    ttf-iosevka-nerd
    ttf-iosevkaterm-nerd
    adobe-source-code-pro-fonts
    adobe-source-sans-fonts
    mkosi
    noto-fonts
    noto-fonts-cjk
    noto-fonts-emoji
    noto-fonts-extra
    ttf-jetbrains-mono-nerd
    ttf-noto-nerd
    ca-certificates-mozilla
    fnott
    fyi
    xwayland-satellite
    adw-gtk-theme
    wireguard-tools
    tailscale
    power-profiles-daemon
    networkmanager
    7zip
    firewalld
    base-devel
    incus
    distrobuilder
    dbus-python
    python-yaml
    python-setproctitle
    uv
    cmake

