#vi:ft=systemd


[Content]
Packages=
    nautilus
    ghostty-nautilus
    yazi
    imagemagick
    wev
    eza
    chafa
    bat
    zoxide
    fzf
    libqalculate
    lazygit
    polkit-kde-agent
    brightnessctl
    pipewire
    pipewire-jack
    pipewire-alsa
    pipewire-audio
    wireplumber
    blueman
    gvfs
    gvfs-mtp
    network-manager-applet
    playerctl
    sway
    swaybg
    swayidle
    swaylock
    system-config-printer
    waybar
    wl-clipboard
    wlsunset
    cliphist
    niri
    sddm
    ghostty
    zathura
    xdg-user-dirs-gtk
    xdg-desktop-portal-gtk
    xdg-desktop-portal-gnome
    waybar
    mako
    rofi
    flatpak
    ttf-iosevka-nerd
    ttf-iosevkaterm-nerd
    adobe-source-code-pro-fonts
    adobe-source-sans-fonts
    noto-fonts
    noto-fonts-cjk
    noto-fonts-emoji
    noto-fonts-extra
    ttf-jetbrains-mono-nerd
    ttf-noto-nerd
    ca-certificates-mozilla
    xwayland-satellite
    adw-gtk-theme
    wireguard-tools
    power-profiles-daemon
    networkmanager
    7zip
    firewalld

