#vi:ft=systemd


[Content]
Packages=
    brightnessctl
    pipewire
    pipewire-jack
    pipewire-alsa
    wireplumber
    pipewire-audio
    blueman
    foot
    grim
    gvfs
    gvfs-mtp
    imv
    lxqt-policykit
    network-manager-applet
    pavucontrol
    playerctl
    rofi
    slurp
    sway
    swaybg
    swayidle
    swaylock
    system-config-printer
    waybar
    wl-clipboard
    wlr-randr
    wlsunset
    xarchiver
    niri
    sddm
    ghostty
    zathura
    imv
    xdg-user-dirs-gtk
    xdg-desktop-portal-gtk
    xdg-desktop-portal-gnome
    xdg-desktop-portal-wlr
    waybar
    mako
    rofi
    fuzzel
    flatpak
    ttf-iosevka-nerd
    ttf-iosevkaterm-nerd
    adobe-source-code-pro-fonts
    adobe-source-sans-fonts
    mkosi
    noto-fonts
    noto-fonts-cjk
    noto-fonts-emoji
    noto-fonts-extra
    ttf-noto-nerd
    ca-certificates-mozilla
    nmtui
    fnott
    fyi
    thunar
    xwayland-satellite
    xwayland
    ttf-jetbrains-mono-nerd
    adw-gtk-theme
    wireguard-tools
    tailscale
    power-profiles-daemon

