# needssslcertforbuild
# SPDX-License-Identifier: LGPL-2.1-or-later
# vi:ft=systemd

[Include]
Include=mkosi-obs

[Distribution]
Distribution=arch

[Config]
Dependencies=base
MinimumVersion=26~devel


[Output]
# OutputDirectory=mkosi.output
# SplitArtifacts=uki,partitions
# Format=disk
ImageId=ParticleOS
ManifestFormat=json
Output=%i_%v_%a

# [Build]
# ToolsTree=default
# ToolsTreeProfiles=misc,runtime,gui
# History=yes
# CacheDirectory=mkosi.cache
# Incremental=yes

[Content]
CacheOnly=always
Bootable=yes
MakeInitrd=yes
BaseTrees=%O/base
InitrdVolatilePackages=
        systemd
        udev
UnifiedKernelImageFormat=%i_%v_%a
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=ParticleOS_*:usr-verity=ParticleOS_*:usr-verity-sig=ParticleOS_*:root=ParticleOS-*:swap=ParticleOS-*:home=ParticleOS-*
        ipe.enforce=0
Hostname=particle-????-????

KernelCommandLine=plymouth.use-simpledrm splash
KernelInitrdModules=default,/drivers/gpu/drm
Splash=/usr/share/systemd/bootctl/splash-arch.bmp
InitrdProfiles=plymouth

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4
Ephemeral=yes
Credentials=
        passwd.plaintext-password.root=particleos
        tty.serial.hvc0.agetty.autologin=particleos
        tty.serial.hvc0.login.noauth=yes
        tty.console.agetty.autologin=particleos
        tty.console.login.noauth=yes
        tty.virtual.tty1.agetty.autologin=particleos
        tty.virtual.tty1.login.noauth=yes

[Validation]
SecureBoot=yes
SignExpectedPcr=yes



#HACK: inline some config from https://github.com/systemd/mkosi/blob/1f811f0524be3096872e79161c8e6ab3e7c2bb1f/mkosi/resources/mkosi-obs/mkosi.conf.d/main.conf

[Build]
History=no
SandboxTrees=/usr/src/packages/SOURCES:/usr/src/packages/SOURCES
BuildSources=/usr/src/packages/OTHER:/usr/src/packages/OTHER
ToolsTree=
CacheDirectory=
Incremental=no
WithNetwork=never

[Distribution]
RepositoryKeyCheck=no
LocalMirror=file:///.build.binaries/

[Output]
OutputDirectory=

[Validation]
SignExpectedPcrCertificate=/usr/src/packages/SOURCES/_projectcert.crt
VerityCertificate=/usr/src/packages/SOURCES/_projectcert.crt
