# needssslcertforbuild
# SPDX-License-Identifier: LGPL-2.1-or-later
# vi:ft=systemd

[Include]
Include=mkosi-obs

[Distribution]
Distribution=arch

[Config]
Profiles=desktop,niri,flathub
MinimumVersion=26~devel


[Output]
SplitArtifacts=uki,partitions
Format=disk
ImageId=ParticleOS
ManifestFormat=json
Output=%i_%v_%a

# [Build]
# ToolsTree=default
# ToolsTreeProfiles=misc,runtime,gui
# History=yes
# CacheDirectory=mkosi.cache
# Incremental=yes

[Content]
CacheOnly=always
InitrdVolatilePackages=
        systemd
        udev
UnifiedKernelImageFormat=%i_%v_%a
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=ParticleOS_*:usr-verity=ParticleOS_*:usr-verity-sig=ParticleOS_*:root=ParticleOS-*:swap=ParticleOS-*:home=ParticleOS-*
        ipe.enforce=0
Hostname=particle-????-????

KernelCommandLine=plymouth.use-simpledrm splash
KernelInitrdModules=default,/drivers/gpu/drm
Splash=/usr/share/systemd/bootctl/splash-arch.bmp
InitrdProfiles=plymouth

Packages=
        acl
        attr
        bash-completion
        btrfs-progs
        ca-certificates
        coreutils
        cpio
        curl
        dbus-broker
        diffutils
        dmidecode
        dosfstools
        e2fsprogs
        efibootmgr
        erofs-utils
        exfatprogs
        file
        findutils
        fish
        fwupd
        gdb
        gdisk
        grep
        gzip
        jq
        kbd
        kexec-tools
        kmod
        less
        man
        mtools
        nftables
        nvme-cli
        opensc
        openssl
        patch
        p11-kit
        pciutils
        pkcs11-provider
        sed
        socat
        strace
        systemd
        tar
        tree
        udev
        unzip
        usbutils
        util-linux
        which
        wireguard-tools
        xxd
        yubikey-manager
        zip
        zstd

VolatilePackages=
        systemd
        udev
        systemd-ukify


Packages=
        archlinux-keyring
        bpf
        ccid
        compsize
        cryptsetup
        dbus-broker-units
        expac
        git
        iproute2
        iputils
        libfido2
        linux
        man-db
        man-pages
        openssh
        pacman
        pcsclite
        perf
        polkit
        procps-ng
        psmisc
        python3
        qrencode
        sbsigntools
        shadow
        systemd-ukify
        tgt
        tpm2-tools
        tpm2-tss
        vim-minimal
        wget
        xz
        zram-generator

RemoveFiles=
        /boot/*-ucode.img

RemoveFiles=/usr/lib/systemd/network/89-ethernet.network


InitrdPackages=
        kbd
        plymouth
        ipe-policy

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4
Ephemeral=yes
Credentials=
        passwd.plaintext-password.root=particleos
        tty.serial.hvc0.agetty.autologin=particleos
        tty.serial.hvc0.login.noauth=yes
        tty.console.agetty.autologin=particleos
        tty.console.login.noauth=yes
        tty.virtual.tty1.agetty.autologin=particleos
        tty.virtual.tty1.login.noauth=yes

[Validation]
SecureBoot=yes
SignExpectedPcr=yes
