# SPDX-License-Identifier: LGPL-2.1-or-later
# vi:ft=systemd

[Distribution]
Distribution=arch


[Config]
Dependencies=base

[Output]
OutputDirectory=mkosi.output
SplitArtifacts=uki,partitions
Format=disk
ImageId=ParticleOS
ManifestFormat=json
Output=%i_%v_%a

[Config]
MinimumVersion=26~devel

[Build]
ToolsTree=default
ToolsTreeProfiles=misc,runtime,gui,package-manager
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Content]
BaseTrees=%O/base
InitrdProfiles=plymouth
InitrdVolatilePackages=
        systemd
        udev
UnifiedKernelImageFormat=%i_%v_%a
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=ParticleOS_*:usr-verity=ParticleOS_*:usr-verity-sig=ParticleOS_*:root=ParticleOS-*:swap=ParticleOS-*:home=ParticleOS-*
        ipe.enforce=0
KernelInitrdModules=default
Hostname=particle-????-????

[Runtime]
RuntimeSize=30G
RAM=4G
CPUs=4
Ephemeral=yes
Credentials=
        passwd.plaintext-password.root=particleos
        tty.serial.hvc0.agetty.autologin=particleos
        tty.serial.hvc0.login.noauth=yes
        tty.console.agetty.autologin=particleos
        tty.console.login.noauth=yes
        tty.virtual.tty1.agetty.autologin=particleos
        tty.virtual.tty1.login.noauth=yes

[Validation]
SecureBoot=yes
SignExpectedPcr=yes
# SPDX-License-Identifier: LGPL-2.1-or-later

# NetworkManager is used in the desktop profiles
RemoveFiles=/usr/lib/systemd/network/89-ethernet.network

KernelCommandLine=plymouth.use-simpledrm splash

KernelInitrdModules=/drivers/gpu/drm

