# needssslcertforbuild
# vi:ft=systemd

[Config]
Dependencies=base,dev

[Include]
Include=mkosi-obs


# HACK: we need this for more than the main image unfortunately
[Build]
History=no
SandboxTrees=/usr/src/packages/SOURCES:/usr/src/packages/SOURCES
BuildSources=/usr/src/packages/OTHER:/usr/src/packages/OTHER
ToolsTree=
CacheDirectory=
Incremental=no
WithNetwork=never

[Distribution]
RepositoryKeyCheck=no
LocalMirror=file:///.build.binaries/

[Output]
OutputDirectory=

[Validation]
SignExpectedPcrCertificate=/usr/src/packages/SOURCES/_projectcert.crt
VerityCertificate=/usr/src/packages/SOURCES/_projectcert.crt
