#vi:ft=systemd

[Config]
Dependencies=base

[Output]
ImageId=DevExt
Output=dev
Format=sysext
Overlay=yes

[Content]
BaseTrees=%O/base
MakeInitrd=no
Packages=
    chezmoi
    base-devel
    incus
    distrobuilder
    dbus-python
    python-yaml
    python-setproctitle
    uv
    cmake
    podman
    distrobox
    toolbox
    mkosi
    ninja
    make
    zig
    go
    osc
