#vi:ft=systemd


[Content]
Packages=
    sway
    niri
    sddm
    ghostty
    zathura
    imv
    xdg-user-dirs-gtk
    xdg-desktop-portal-gtk
    xdg-desktop-portal-gnome
    xdg-desktop-portal-wlr
    waybar
    mako
    rofi

