# SPDX-License-Identifier: LGPL-2.1-or-later
# vi:ft=systemd

[Config]
Profiles=desktop,niri,flathub

[Output]
SplitArtifacts=uki,partitions
Format=directory
ImageId=base
Output=base

[Content]
CleanPackageMetadata=no
MakeInitrd=no
Packages=
        acl
        attr
        bash-completion
        btrfs-progs
        ca-certificates
        coreutils
        cpio
        curl
        dbus-broker
        diffutils
        dmidecode
        dosfstools
        e2fsprogs
        efibootmgr
        erofs-utils
        exfatprogs
        file
        findutils
        fish
        fwupd
        gdb
        gdisk
        grep
        gzip
        jq
        kbd
        kexec-tools
        kmod
        less
        man
        mtools
        nano
        nftables
        nvme-cli
        opensc
        openssl
        patch
        p11-kit
        pciutils
        pkcs11-provider
        sed
        socat
        strace
        systemd
        tar
        tree
        udev
        unzip
        usbutils
        util-linux
        which
        wireguard-tools
        xxd
        yubikey-manager
        zip
        zstd

VolatilePackages=
        systemd
        udev



[Validation]
SignExpectedPcr=yes
