# SPDX-License-Identifier: LGPL-2.1-or-later
# vi:ft=systemd

[Config]
Profiles=desktop,niri,flathub

[Output]
bootable=no
Format=directory
ImageId=base
Output=base

[Content]
CleanPackageMetadata=no
MakeInitrd=no
Packages=
        acl
        attr
        bash-completion
        btrfs-progs
        ca-certificates
        coreutils
        cpio
        curl
        dbus-broker
        diffutils
        dmidecode
        dosfstools
        e2fsprogs
        efibootmgr
        erofs-utils
        exfatprogs
        file
        findutils
        fish
        fwupd
        gdb
        gdisk
        grep
        gzip
        jq
        kbd
        kexec-tools
        kmod
        less
        man
        mtools
        nftables
        nvme-cli
        opensc
        openssl
        patch
        p11-kit
        pciutils
        pkcs11-provider
        sed
        socat
        strace
        systemd
        tar
        tree
        udev
        unzip
        usbutils
        util-linux
        which
        wireguard-tools
        xxd
        yubikey-manager
        zip
        zstd

VolatilePackages=
        systemd
        udev
        systemd-ukify


Packages=
        archlinux-keyring
        bpf
        ccid
        compsize
        cryptsetup
        dbus-broker-units
        expac
        git
        iproute2
        iputils
        libfido2
        linux
        man-db
        man-pages
        openssh
        pacman
        pcsclite
        perf
        polkit
        procps-ng
        psmisc
        python3
        qrencode
        sbsigntools
        shadow
        systemd-ukify
        tgt
        tpm2-tools
        tpm2-tss
        vim-minimal
        wget
        xz
        zram-generator

RemoveFiles=
        /boot/*-ucode.img

RemoveFiles=/usr/lib/systemd/network/89-ethernet.network
